
spring:
  application:
    name: task
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  mail:
    from: meharet.salmanov@gmail.com
    host: smtp.gmail.com
    port: 587
    username: meharet.salmanov@gmail.com
    password: ikpa qauo siwk reag
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  site-url: http://localhost:8080

security:
  jwt:
    secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    access-token-validity-time: 86400000
    refresh-token-validity-time: 86400000